/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 01-16-2023
 * @last modified by  : Boussalah Aymen
**/


public  class debugTest {
    /**
    * @description 
    * @author Boussalah Aymen | 01-16-2023 
    **/
    public static void write(){
        System.debug('first debug');
        System.debug('Second debug');
    }
}